# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LjG_A4kfBcyT4xeuuOrNmtmxEaSYmcdv
"""

from PIL import Image
import os,glob
import numpy as np

def test(testset_folder, model_name):

  # 적용해볼 이미지 
  test_image = glob.glob(testset_folder+'/*.jpg')

    # 이미지 resize
  for i,f in enumerate(test_image):
      img=Image.open(f)
      img=img.convert("RGB")

      img=img.resize((64,64))
      data=np.asarray(img)                      
      X = np.array(data)
      X = X.astype("float") / 256
      X = X.reshape(-1, 64, 64,3)
    # 예측
      pred = model.predict(X)  
      result = [np.argmax(value) for value in pred]   # 예측 값 중 가장 높은 클래스 반환
      print('New data category : ',categories[result[0]])